### ISSUE TITLE
Plugin released, but not pubished

### ISSUE THREAD

**Issue by Jaff** [edwgiz/maven-shaded-log4j-transformer#41]
We're not able to download this version from any maven repos

**Comment by dwightmulcahy** [comment]
Yeah, I am only seeing 2.15 on the central repo.

https://mvnrepository.com/artifact/com.github.edwgiz/maven-shade-plugin.log4j2-cachefile-transformer

https://repo1.maven.org/maven2/com/github/edwgiz/maven-shade-plugin.log4j2-cachefile-transformer/

**Comment by michielvd** [comment]
Was looking for the same thing. Apparently since 2.16 the group and artifact id have changed as well as the package of the class

![afbeelding](https://user-images.githubusercontent.com/1658666/151531734-69223f15-f829-4a32-bf74-79342d7d8406.png)

Newest releases can be found here https://search.maven.org/artifact/io.github.edwgiz/log4j-maven-shade-plugin-extensions/2.17.1/jar

So you should update to
```
            <groupId>io.github.edwgiz</groupId>
            <artifactId>log4j-maven-shade-plugin-extensions</artifactId>
```
and
```
<transformer implementation="io.github.edwgiz.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer"></transformer>
```
