### ISSUE TITLE
Redirecting users to `log4j-transform-maven-shade-plugin-extensions`

### ISSUE THREAD

**Issue by vy** [edwgiz/maven-shaded-log4j-transformer#46]
@edwgiz, would you mind updating the README to share the following, please?

1. this project has become a part of the official Log4j distribution in [log4j-transform-maven-shade-plugin-extensions](/apache/logging-log4j-transform/tree/main/log4j-transform-maven-shade-plugin-extensions)
2. Its future development will continue there
3. All existing and future users are recommended to migrate to this successor project

**Comment by edwgiz** [comment]
Yeah, sure @vy 
I would be glad updating my README.

To do that it's worth assuring the users can switch to the new plugin artifact smoothly. I see 3 prerequisites to meet:

1. the `org.apache.logging.log4j:log4j-maven-shade-plugin-extensions` artifact is available in maven central like other log4j official artifacts
2. I've spotted some old reference in new [README](https://github.com/apache/logging-log4j-transform/tree/main/log4j-transform-maven-shade-plugin-extensions#readme):  `<groupId>io.github.edwgiz</groupId>`. Please lemme know if you want I make PR.
3.Also before you shared the artifact, I would make additional PR in order to merge the changes accumulated in my repo since my previous code transfer, hope it's possible

**Comment by vy** [comment]
> 1. the `org.apache.logging.log4j:log4j-maven-shade-plugin-extensions` artifact is available in maven central like other log4j official artifacts

Your gem has already been released! [Check it out!](https://central.sonatype.com/artifact/org.apache.logging.log4j/log4j-transform-maven-shade-plugin-extensions/0.1.0)

> 2. I've spotted some old reference in new [README](https://github.com/apache/logging-log4j-transform/tree/main/log4j-transform-maven-shade-plugin-extensions#readme):  `<groupId>io.github.edwgiz</groupId>`. Please let me know if you want I make PR.
> 3. Also before you shared the artifact, I would make additional PR in order to merge the changes accumulated in my repo since my previous code transfer, hope it's possible

I think we are not on the same page here. _You_ developed the plugin and donated it to the ASF Logging Services, which is an umbrella project for log4j, log4cxx, etc. We just made it a part of the official Log4j distribution, since we think it addresses a common pain point and it gets the job done. Of course, these changes imply that the Logging Services will be responsible for maintaining the plugin, but it is still your plugin. We would be more than happy if you keep on maintaining it. If you would like to contribute to other Log4j projects, that is even more awesome! Go ahead.

All in all, please keep those PRs coming! :100:

**Comment by edwgiz** [comment]
@vy, awesome :)

waiting for PR approval
https://github.com/apache/logging-log4j-transform/pull/42

**Comment by edwgiz** [comment]
@vy , thank you for your participation, I think the migration is done
